/**
 * Emits supabase/seed.sql from lib/products/seed-data.ts (idempotent upsert by slug).
 * Run: node --import tsx scripts/generate-seed-sql.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { SEED_PRODUCTS } from "../lib/products/seed-data";

const q = (v: string | null) => (v === null ? "null" : `'${v.replace(/'/g, "''")}'`);

const rows = SEED_PRODUCTS.map((p) =>
  `  (${q(p.id)}, ${q(p.name)}, ${q(p.slug)}, ${q(p.description)}, ${q(p.shortDescription)}, ${q(p.category)}, ${p.price.toFixed(2)}, ${q(p.imageUrl)}, ${q(p.size)}, ${q(p.colourName)}, ${q(p.colourHex)}, ${q(p.finish)}, ${q(p.coverage)}, ${p.stockQuantity}, ${p.isActive}, ${p.isFeatured})`,
);

const sql = `-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.
-- Source of truth: lib/products/seed-data.ts
insert into public.products
  (id, name, slug, description, short_description, category, price, image_url, size, colour_name, colour_hex, finish, coverage, stock_quantity, is_active, is_featured)
values
${rows.join(",\n")}
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  short_description = excluded.short_description,
  category = excluded.category,
  price = excluded.price,
  image_url = excluded.image_url,
  size = excluded.size,
  colour_name = excluded.colour_name,
  colour_hex = excluded.colour_hex,
  finish = excluded.finish,
  coverage = excluded.coverage,
  stock_quantity = excluded.stock_quantity,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured,
  updated_at = now();
`;

writeFileSync(join(process.cwd(), "supabase", "seed.sql"), sql);
console.log(`Wrote supabase/seed.sql with ${SEED_PRODUCTS.length} products`);
